# Creation of Array (1D,2D and Multidimennsional array)

In [2]:
#Exp no. : 5

In [4]:
#Aim : Creation of Array (1D,2D and Multidimennsional array) using numpy

In [22]:
#Name :  Devesh J Arbat 
#Roll no. : 06
#Section : A

In [8]:
import numpy as np

In [10]:
arr1=np.array([10,20,30,40,50])


In [12]:
arr1

array([10, 20, 30, 40, 50])

In [14]:
arr2=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [16]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [18]:
arr3=np.array([[10,20,30,40,50],[60,70,80,90,100],[15,25,35,45,55]])

In [20]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 15,  25,  35,  45,  55]])